package submissionsystem.userinterface;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import submissionsystem.*;
/**
 * A class to create a login frame to submission system
 * @author Abdullah Talayhan
 */
public class LoginFrame extends javax.swing.JFrame {
    
    Client client;
    /**
     * Creates new form loginFrame
     */
    public LoginFrame() {
        initComponents();
        stdRdButton.setActionCommand("Student");
        insRdButton.setActionCommand("Instructor");
        client = new Client();
        client.connectServer();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        emailLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        stdRdButton = new javax.swing.JRadioButton();
        insRdButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        emailLabel.setText("E-mail:");

        passLabel.setText("Password:");

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        buttonGroup.add(stdRdButton);
        stdRdButton.setSelected(true);
        stdRdButton.setText("Student");
        stdRdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdRdButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(insRdButton);
        insRdButton.setText("Instructor");
        insRdButton.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabel)
                            .addComponent(stdRdButton)
                            .addComponent(insRdButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(login))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passLabel))
                .addGap(11, 11, 11)
                .addComponent(stdRdButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insRdButton)
                    .addComponent(login))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        // type
        client.sendUTFDataToServer("LOGIN_OPEN");
        client.sendUTFDataToServer(buttonGroup.getSelection().getActionCommand());
        //e-mail
        client.sendUTFDataToServer(idField.getText());
        // password
        client.sendUTFDataToServer(String.valueOf(passField.getPassword()));
        
        String ans = client.getUTFDataFromServer();

        if (ans.equals("YES")) {
                //int id = client.getIntDataFromServer();
            //client.setEmail(idField.getText());
            client.setClientInfo(client.getIntDataFromServer(), client.getUTFDataFromServer(), idField.getText());
                if(buttonGroup.getSelection().getActionCommand().equals("Student")) {
                    StudentMain stdMainFrame = new StudentMain( client);
                    stdMainFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    stdMainFrame.setLocationRelativeTo(this);
                    stdMainFrame.setVisible(true);
                    
                
                }
                else {
                   InsMain insMainFrame = new InsMain(client);
                   insMainFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                   insMainFrame.setLocationRelativeTo(this);
                   insMainFrame.setVisible(true);
                }
                //String name = client.getUTFDataFromServer();
                
                //System.out.println(name);
                dispose();
        } else {
                System.out.println("Wrong User name or password");
                JOptionPane.showMessageDialog(this, "Wrong username or password.", "Call-IDE Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void stdRdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdRdButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdRdButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JRadioButton insRdButton;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JRadioButton stdRdButton;
    // End of variables declaration//GEN-END:variables
}
