package submissionsystem.userinterface;

import javax.swing.JOptionPane;

/**
 *
 * @author Abdullah Talayhan
 */
public class RegFrame extends javax.swing.JFrame {

    Client client;
    String email;
    /**
     * Creates new form RegFrame
     */
    public RegFrame() {
        initComponents();
    }
    
    public RegFrame(Client pclient, String mail) {
        client = pclient;
        email = mail;
        initComponents();
        emailLabel.setText(email);
        stdRdButton.setActionCommand("Student");
        insRdButton.setActionCommand("Instructor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        emailPrpLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        namePrpLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        surPrpLabel = new javax.swing.JLabel();
        surnameField = new javax.swing.JTextField();
        idPrpLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        regButton = new javax.swing.JButton();
        pass1Label = new javax.swing.JLabel();
        pass2Label = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        confPassField = new javax.swing.JPasswordField();
        passPrpLabel = new javax.swing.JLabel();
        stdRdButton = new javax.swing.JRadioButton();
        insRdButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");

        emailPrpLabel.setText("E-mail: ");

        emailLabel.setText("example@example.com");

        namePrpLabel.setText("Name: ");

        surPrpLabel.setText("Surname:");

        idPrpLabel.setText("ID:");

        regButton.setText("Register");
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });

        pass1Label.setText("Password:");

        pass2Label.setText("Confirm Password:");

        passPrpLabel.setText("(Min. 8 characters)");

        buttonGroup.add(stdRdButton);
        stdRdButton.setSelected(true);
        stdRdButton.setText("Student");
        stdRdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdRdButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(insRdButton);
        insRdButton.setText("Instructor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stdRdButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insRdButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(regButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pass1Label)
                            .addComponent(surPrpLabel)
                            .addComponent(namePrpLabel)
                            .addComponent(emailPrpLabel)
                            .addComponent(idPrpLabel)
                            .addComponent(pass2Label))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passField)
                            .addComponent(idField)
                            .addComponent(nameField)
                            .addComponent(surnameField)
                            .addComponent(confPassField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passPrpLabel)
                                    .addComponent(emailLabel))
                                .addGap(0, 51, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailPrpLabel)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namePrpLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surPrpLabel)
                    .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPrpLabel)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pass1Label)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(passPrpLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass2Label)
                    .addComponent(confPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regButton)
                    .addComponent(insRdButton)
                    .addComponent(stdRdButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        // TODO add your handling code here:
        
        String name = nameField.getText();
        String surname = surnameField.getText();
        String id = idField.getText();
        String pass = String.valueOf(passField.getPassword());
        String confPass = String.valueOf(confPassField.getPassword());
        System.out.println(pass + " " + confPass);
        if(!pass.equals(confPass)  || pass.length() < 8) {
            if(!pass.equals(confPass) ) {
                JOptionPane.showMessageDialog(this,"Passwords do not match","Call-IDE error",JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this,"Password length should be min. 8","Call-IDE error",JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(name.length() > 20) {
            JOptionPane.showMessageDialog(this,"Name is too long.","Call-IDE error",JOptionPane.ERROR_MESSAGE);
        }
        else {
            client.sendUTFDataToServer("REGISTER_ATTEMPT");
            client.sendUTFDataToServer(buttonGroup.getSelection().getActionCommand());
            client.sendUTFDataToServer(id);
            client.sendUTFDataToServer(name + " " + surname);
            client.sendUTFDataToServer(pass);
            client.sendUTFDataToServer(emailLabel.getText());
            
            //System.out.println("reg complete");
            JOptionPane.showMessageDialog(this,"Registration Complete","Call-IDE Submission System",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            
        }
        
         
        
    }//GEN-LAST:event_regButtonActionPerformed

    private void stdRdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdRdButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdRdButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPasswordField confPassField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailPrpLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idPrpLabel;
    private javax.swing.JRadioButton insRdButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel namePrpLabel;
    private javax.swing.JLabel pass1Label;
    private javax.swing.JLabel pass2Label;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passPrpLabel;
    private javax.swing.JButton regButton;
    private javax.swing.JRadioButton stdRdButton;
    private javax.swing.JLabel surPrpLabel;
    private javax.swing.JTextField surnameField;
    // End of variables declaration//GEN-END:variables
}
