package submissionsystem.userinterface;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Abdullah Talayhan
 */
public class VerifyEmail extends javax.swing.JFrame {
    
    Client client = null;
    RegFrame regFrame;
    /**
     * Creates new form Submission_Login
     */
    public VerifyEmail(Client pclient) {
        client = pclient;
        
		addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent e) {
				client.closeConnection();
			}
		});
        initComponents();
        confirmVerifCodeButton.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        mailField = new javax.swing.JTextField();
        verifLabel = new javax.swing.JLabel();
        verifCodeField = new javax.swing.JTextField();
        confirmVerifCodeButton = new javax.swing.JButton();
        sendVerifCodeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-mail Verification");

        emailLabel.setText("E-mail:");

        mailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailFieldActionPerformed(evt);
            }
        });

        verifLabel.setText("Verification Code: ");

        confirmVerifCodeButton.setText("Confirm");
        confirmVerifCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmVerifCodeButtonActionPerformed(evt);
            }
        });

        sendVerifCodeButton.setText("Send Code");
        sendVerifCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendVerifCodeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verifLabel)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mailField, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(verifCodeField))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sendVerifCodeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmVerifCodeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendVerifCodeButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifLabel)
                    .addComponent(verifCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmVerifCodeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailFieldActionPerformed

    private void sendVerifCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendVerifCodeButtonActionPerformed
        // TODO add your handling code here:
        // send e-mail
        client.sendUTFDataToServer("REGISTER_OPEN");
        mailField.setEditable(false);
        client.sendUTFDataToServer(mailField.getText());
        String ans = client.getUTFDataFromServer();
        if(ans.equals("IS_EMAIL")) {
            confirmVerifCodeButton.setEnabled(true);
        }
        else {
            confirmVerifCodeButton.setEnabled(false);
            String insCode = client.getUTFDataFromServer();
            JOptionPane.showMessageDialog(this, "Wrong e-mail address, your institute code is: " + insCode, "Call-IDE Error!", JOptionPane.ERROR_MESSAGE);
            mailField.setEditable(true);
        }
    }//GEN-LAST:event_sendVerifCodeButtonActionPerformed

    private void confirmVerifCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmVerifCodeButtonActionPerformed

        // not valid email
        client.sendUTFDataToServer(verifCodeField.getText());
        if(client.getUTFDataFromServer().equals("ACCEPT_USER")) {
                //System.out.println(client.getUTFDataFromServer());

                regFrame = new RegFrame(client, mailField.getText());

                regFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                regFrame.setLocationRelativeTo(this);
                regFrame.setVisible(true);


                dispose();
        }

        
        
    }//GEN-LAST:event_confirmVerifCodeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmVerifCodeButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mailField;
    private javax.swing.JButton sendVerifCodeButton;
    private javax.swing.JTextField verifCodeField;
    private javax.swing.JLabel verifLabel;
    // End of variables declaration//GEN-END:variables
}
