/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package submissionsystem;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.WindowConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abdullah.talayhan-ug
 */
public class InsMain extends javax.swing.JFrame {

    Client client;
    /**
     * Creates new form InsMain
     */
    public InsMain(Client pclient) {
        client = pclient;
        
        initComponents();
        init();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseList = new javax.swing.JList();
        addCourseButton = new javax.swing.JButton();
        coursePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        courseTitleLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        pubAssignButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        showAssignButton = new javax.swing.JButton();
        courseDescLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("My Courses: ");

        courseList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "CS102-02", "CS223-01", "CS319-02" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(courseList);

        addCourseButton.setText("Add Course");
        addCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseButtonActionPerformed(evt);
            }
        });

        coursePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Course Name: ");

        courseTitleLabel.setText("CS102-02");

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "29866079", "lab01", "04.10.2016",  new Boolean(false),  new Boolean(false)},
                {"2", "61618675", "lab02", "11.10.2016",  new Boolean(false),  new Boolean(false)},
                {"3", "59022017", "lab03", "18.10.2016", null,  new Boolean(true)},
                {"4", "44546138", "lab04", "25.10.2016",  new Boolean(true),  new Boolean(true)},
                {"5", "60437855", "lab05", "02.11.2016", null,  new Boolean(true)},
                {"6", "67873316", "lab06", "16.11.2016", null,  new Boolean(true)},
                {"7", "27908627", "lab07", "23.11.2016",  new Boolean(true), null},
                {"8", "17570421", "lab08", "30.11.2016", null,  new Boolean(true)},
                {"9", "64320744", "lab09", "06.11.2016", null,  new Boolean(true)}
            },
            new String [] {
                "No ▲", "ID", "Assignment", "Due Date", "Auto Grading", "Moss Check"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(studentTable);

        pubAssignButton.setText("Send Assignment");
        pubAssignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pubAssignButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Send E-mail");

        showAssignButton.setText("Assignments");

        courseDescLabel.setText("courseDesLabel");

        javax.swing.GroupLayout coursePanelLayout = new javax.swing.GroupLayout(coursePanel);
        coursePanel.setLayout(coursePanelLayout);
        coursePanelLayout.setHorizontalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coursePanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(courseTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courseDescLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coursePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(coursePanelLayout.createSequentialGroup()
                                .addComponent(showAssignButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pubAssignButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        coursePanelLayout.setVerticalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(courseTitleLabel)
                    .addComponent(courseDescLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pubAssignButton)
                    .addComponent(jButton3)
                    .addComponent(showAssignButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addCourseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(coursePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coursePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCourseButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseButtonActionPerformed
        // TODO add your handling code here:
        CourseReg createCourseFrame = new CourseReg(client, this);
        createCourseFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        createCourseFrame.setVisible(true);
    }//GEN-LAST:event_addCourseButtonActionPerformed

    private void pubAssignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pubAssignButtonActionPerformed
        // TODO add your handling code here:
        SendAssignment sendFrame = new SendAssignment(client, courseTitleLabel.getText());
        sendFrame.setVisible(true);
    }//GEN-LAST:event_pubAssignButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void init() {
        
        courseList.setModel(new DefaultListModel());
        client.sendUTFDataToServer("GET_COURSES");
        courseArrList = (ArrayList)client.getObjectFromServer();
        model = (DefaultListModel) courseList.getModel();
        //model.clear();
        for(String s : courseArrList) {
            model.addElement(s);
        }
        courseList.setModel(model);
        courseList.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent evt) {
                
                
                JList list = (JList) evt.getSource();
                int index = list.getSelectedIndex();
                if(index != -1) {
                constructCoursePanel(index);
                }
            }
        });
    }
    
    public void updateCourseList() {
        courseList.setModel(new DefaultListModel());
        client.sendUTFDataToServer("GET_COURSES");
        courseArrList = (ArrayList)client.getObjectFromServer();
        model = (DefaultListModel) courseList.getModel();
        //model.clear();
        for(String s : courseArrList) {
            model.addElement(s);
        }
        courseList.setModel(model);
    }
    public void constructCoursePanel(int index) {
        String course = (String) model.getElementAt(index);
        courseTitleLabel.setText(course);
        
        client.sendUTFDataToServer("CONSTRUCT_STUDENT_PANEL");
        client.sendUTFDataToServer(course);
        
        DefaultTableModel panelTableModel = (DefaultTableModel)client.getObjectFromServer();
        studentTable.setModel(panelTableModel);
    }
    
    
    // other vairables
    public ArrayList<String> courseArrList;
    public DefaultListModel model;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseButton;
    private javax.swing.JLabel courseDescLabel;
    private javax.swing.JList courseList;
    private javax.swing.JPanel coursePanel;
    private javax.swing.JLabel courseTitleLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton pubAssignButton;
    private javax.swing.JButton showAssignButton;
    private javax.swing.JTable studentTable;
    // End of variables declaration//GEN-END:variables

   
}
