package submissionsystem;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdullah Talayhan
 */
public class CourseReg extends javax.swing.JFrame {

    Client client;
    String cKey;
    InsMain insMain;
    /**
     * Creates new form CourseReg
     */
    public CourseReg( Client pclient, InsMain prev) {
        insMain =  prev;
        client = pclient;
        initComponents();
        promptLabel.setVisible(false);
        copyToClipBtn.setVisible(false);
        client.sendUTFDataToServer("GET_INS");
        insLabel.setText(client.getUTFDataFromServer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ccLabel = new javax.swing.JLabel();
        courseCodeField = new javax.swing.JTextField();
        cTLabel = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        createCourseBtn = new javax.swing.JButton();
        secNoLaebl = new javax.swing.JLabel();
        courseSectionField = new javax.swing.JTextField();
        insCodeLabel = new javax.swing.JLabel();
        insLabel = new javax.swing.JLabel();
        promptLabel = new javax.swing.JLabel();
        copyToClipBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Course");

        ccLabel.setText("Course Code:");

        courseCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseCodeFieldActionPerformed(evt);
            }
        });

        cTLabel.setText("Course Title:");

        createCourseBtn.setText("Create Class");
        createCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCourseBtnActionPerformed(evt);
            }
        });

        secNoLaebl.setText("Section No:");

        insCodeLabel.setText("Institude Code: ");

        insLabel.setText("bilkent.edu.tr");

        promptLabel.setText("Class Key for CS101-03 :   QX7V6695D");

        copyToClipBtn.setText("Copy ");
        copyToClipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyToClipBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ccLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(courseCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(secNoLaebl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(courseSectionField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(promptLabel)
                            .addGap(18, 18, 18)
                            .addComponent(copyToClipBtn))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cTLabel)
                                .addComponent(insCodeLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(insLabel)
                                .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(createCourseBtn)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccLabel)
                    .addComponent(courseCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secNoLaebl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseSectionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTLabel)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insCodeLabel)
                    .addComponent(insLabel))
                .addGap(18, 18, 18)
                .addComponent(createCourseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promptLabel)
                    .addComponent(copyToClipBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCourseBtnActionPerformed
        // TODO add your handling code here:
        
        String finalCode = courseCodeField.getText() + "-" + courseSectionField.getText();
        finalCode = finalCode.toLowerCase();
        String title = titleField.getText();
        client.sendUTFDataToServer("CREATE_COURSE");
        client.sendUTFDataToServer(finalCode);
        client.sendUTFDataToServer(title);
        String ans = client.getUTFDataFromServer();
        if(ans.equals("COURSE_CREATED")) {
            cKey = client.getUTFDataFromServer();
            insMain.updateCourseList();
            promptLabel.setText("Class Key for " + finalCode +  ": " +  cKey);
            promptLabel.setVisible(true);
            copyToClipBtn.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "Class Already Exists", "Call-IDE Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_createCourseBtnActionPerformed

    private void courseCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseCodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseCodeFieldActionPerformed

    private void copyToClipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyToClipBtnActionPerformed
        // TODO add your handling code here:
        StringSelection selection = new StringSelection(cKey);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        if(cKey != null) {
            clipboard.setContents(selection, selection);
        }
    }//GEN-LAST:event_copyToClipBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cTLabel;
    private javax.swing.JLabel ccLabel;
    private javax.swing.JButton copyToClipBtn;
    private javax.swing.JTextField courseCodeField;
    private javax.swing.JTextField courseSectionField;
    private javax.swing.JButton createCourseBtn;
    private javax.swing.JLabel insCodeLabel;
    private javax.swing.JLabel insLabel;
    private javax.swing.JLabel promptLabel;
    private javax.swing.JLabel secNoLaebl;
    private javax.swing.JTextField titleField;
    // End of variables declaration//GEN-END:variables
}
