package submissionsystem;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import net.lingala.zip4j.core.*;
import net.lingala.zip4j.exception.ZipException;
import net.lingala.zip4j.model.*;
import net.lingala.zip4j.util.*;
/**
 *
 * @author Abdullah Talayhan
 */
public class SendAssignment extends javax.swing.JFrame {

    /**
     * Creates new form SendAssignment
     */
    
    Client client;
    File toSend;
    String assignmentPath;
    String courseCode;
    FileInputStream fis;
    
    public SendAssignment(Client pclient, String code) {
        client = pclient;
        courseCode = code;
       
        initComponents();
        courseName.setText(courseCode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coursePrpLabel = new javax.swing.JLabel();
        asgnPrpLabel = new javax.swing.JLabel();
        duePrpLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        dueDate = new javax.swing.JTextField();
        browseBtn = new javax.swing.JButton();
        asgnFilePrp = new javax.swing.JLabel();
        publishBtn = new javax.swing.JButton();
        courseName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Publish Assignment");

        coursePrpLabel.setText("Course:");

        asgnPrpLabel.setText("Assignment Name: ");

        duePrpLabel.setText("Due Date: ");

        dueDate.setText("YYYY-MM-DD");
        dueDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueDateActionPerformed(evt);
            }
        });

        browseBtn.setText("Browse");
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });

        asgnFilePrp.setText("Assignment File");

        publishBtn.setText("Publish");
        publishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publishBtnActionPerformed(evt);
            }
        });

        courseName.setText("CS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asgnPrpLabel)
                            .addComponent(duePrpLabel)
                            .addComponent(coursePrpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseName)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(dueDate))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(asgnFilePrp)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(browseBtn)
                                .addGap(58, 58, 58)))
                        .addGap(100, 100, 100)
                        .addComponent(publishBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coursePrpLabel)
                    .addComponent(courseName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asgnPrpLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duePrpLabel)
                    .addComponent(dueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(publishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(asgnFilePrp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseBtn)))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void publishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishBtnActionPerformed
        // TODO add your handling code here:
        long length = toSend.length();
        
        if(length > Integer.MAX_VALUE) {
            JOptionPane.showMessageDialog(this, "Assignment file is more than 2 GB", "Call-IDE Error!", JOptionPane.ERROR);

        }
        else {
            
                client.sendUTFDataToServer("PUBLISH_ASSIGNMENT");
                
                long millis=System.currentTimeMillis();
                client.sendUTFDataToServer(nameField.getText().toLowerCase().replace("_", "-"));
                client.sendObjectToServer(Date.valueOf(dueDate.getText()));
                client.sendObjectToServer(new Date(millis));
                client.sendUTFDataToServer(courseCode);
                //construct toSend here
                //client.sendUTFDataToServer(toSend.getName());
                
                // send length
                //client.sendIntDataToServer((int)length);
            try {
                ZipParameters zipParams = new ZipParameters();
                zipParams.setCompressionMethod(Zip4jConstants.COMP_DEFLATE);
                zipParams.setCompressionLevel(Zip4jConstants.DEFLATE_LEVEL_NORMAL);
                
                String compressedPath = toSend.getParent() + "/" + nameField.getText().toLowerCase() + ".zip";
                ZipFile compressedFile = new ZipFile(compressedPath);
                
                compressedFile.addFolder(toSend, zipParams);
                File toSendZip = new File(compressedPath);
                
                fis = new FileInputStream(toSendZip);
                byte[] data = new byte[(int)toSendZip.length()];
                fis.read(data);
                fis.close();
               
                client.sendObjectToServer(data);
                
                
                String ans = client.getUTFDataFromServer();
                if(ans.equals("PUBLISHED")) {
                    JOptionPane.showMessageDialog(this, "Assignment Published", "Call-IDE Submission System", JOptionPane.INFORMATION_MESSAGE);
                }   
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SendAssignment.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SendAssignment.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ZipException ex) {
                Logger.getLogger(SendAssignment.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
        
    }//GEN-LAST:event_publishBtnActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.showOpenDialog(null);
        
        toSend = chooser.getSelectedFile();
        
    }//GEN-LAST:event_browseBtnActionPerformed

    private void dueDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dueDateActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asgnFilePrp;
    private javax.swing.JLabel asgnPrpLabel;
    private javax.swing.JButton browseBtn;
    private javax.swing.JLabel courseName;
    private javax.swing.JLabel coursePrpLabel;
    private javax.swing.JTextField dueDate;
    private javax.swing.JLabel duePrpLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton publishBtn;
    // End of variables declaration//GEN-END:variables
}
