/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uidesign;


import java.awt.*;
import java.awt.event.*;
import java.io.*;
import javax.swing.*;
import javax.imageio.ImageIO;
import org.fife.ui.rsyntaxtextarea.*;
import org.fife.ui.rtextarea.*;
import java.util.ArrayList;
import FileOperations.*;
import RunUtils.*;
import FileExplorer.*;

/**
 *
 * @author bahadir.tuluce-ug
 */
public class MainFrame extends javax.swing.JFrame {
    
    private int wordCounter;
    private SearchResult searchResult;  
    
    /** Creates new form MainFrame. */
    public MainFrame() throws IOException {
        textAreas = new ArrayList<RSyntaxTextArea>();
        files = new ArrayList<File>();
        untitledCount = 1;
        initComponents();
        newFile();
        addExplorer();
        initFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        preferencesFrame = new javax.swing.JFrame();
        idePreferencesPanel = new javax.swing.JPanel();
        newCheck = new javax.swing.JCheckBox();
        openCheck = new javax.swing.JCheckBox();
        saveCheck = new javax.swing.JCheckBox();
        undoCheck = new javax.swing.JCheckBox();
        redoCheck = new javax.swing.JCheckBox();
        compileCheck = new javax.swing.JCheckBox();
        runCheck = new javax.swing.JCheckBox();
        compileRunCheck = new javax.swing.JCheckBox();
        resetCheck = new javax.swing.JCheckBox();
        jarCheck = new javax.swing.JCheckBox();
        javadocCheck = new javax.swing.JCheckBox();
        apiCheck = new javax.swing.JCheckBox();
        helpCheck = new javax.swing.JCheckBox();
        loginCheck = new javax.swing.JCheckBox();
        toolbarPreferencesPanel = new javax.swing.JPanel();
        themeLabel = new javax.swing.JLabel();
        fontLabel = new javax.swing.JLabel();
        indentLabel = new javax.swing.JLabel();
        lineNumbersCheck = new javax.swing.JCheckBox();
        themeComboBox = new javax.swing.JComboBox<>();
        selectFontButton = new javax.swing.JButton();
        fontTextField = new javax.swing.JTextField();
        indentTextField = new javax.swing.JTextField();
        autosaveTextField = new javax.swing.JTextField();
        minsLabel = new javax.swing.JLabel();
        showHelpCheck = new javax.swing.JCheckBox();
        autosaveCheck = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        fontTextField1 = new javax.swing.JTextField();
        selectFontButton1 = new javax.swing.JButton();
        findReplaceFrame = new javax.swing.JFrame();
        findReplacePanel = new javax.swing.JPanel();
        replaceButton = new javax.swing.JButton();
        replaceAllButton = new javax.swing.JButton();
        findLabel = new javax.swing.JLabel();
        replaceLabel = new javax.swing.JLabel();
        findTextField = new javax.swing.JTextField();
        replaceTextField = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        mainSplitPane = new javax.swing.JSplitPane();
        topSplitPane = new javax.swing.JSplitPane();
        explorerScrollPane = new javax.swing.JScrollPane();
        placeHolderFileExplorer = new javax.swing.JTree();
        editorAndMethodSummaryPanel = new javax.swing.JPanel();
        topLeftSplitPane = new javax.swing.JSplitPane();
        textTabs = new javax.swing.JTabbedPane();
        methodSummaryScrollPane = new javax.swing.JScrollPane();
        methodSummary = new javax.swing.JTree();
        outputsPanel = new javax.swing.JPanel();
        outputTabs = new javax.swing.JTabbedPane();
        statusPanel = new javax.swing.JPanel();
        statusScrollPane = new javax.swing.JScrollPane();
        statusArea = new javax.swing.JTextArea();
        consoleOutputPanel = new javax.swing.JPanel();
        consoleOutputScrollPane = new javax.swing.JScrollPane();
        consoleOutputArea = new javax.swing.JTextArea();
        consoleInputField = new javax.swing.JTextField();
        compilerOutputPanel = new javax.swing.JPanel();
        compilerOutputScrollPane = new javax.swing.JScrollPane();
        compilerOutputArea = new javax.swing.JTextArea();
        toolbarPanel = new javax.swing.JPanel();
        newTool = new javax.swing.JButton();
        openTool = new javax.swing.JButton();
        saveTool = new javax.swing.JButton();
        undoTool = new javax.swing.JButton();
        redoTool = new javax.swing.JButton();
        resetTool = new javax.swing.JButton();
        javadocTool = new javax.swing.JButton();
        jarTool = new javax.swing.JButton();
        compileTool = new javax.swing.JButton();
        runTool = new javax.swing.JButton();
        compileRunTool = new javax.swing.JButton();
        apiTool = new javax.swing.JButton();
        helpTool = new javax.swing.JButton();
        loginTool = new javax.swing.JButton();
        closeTool = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newFileButton = new javax.swing.JMenuItem();
        newProjectButton = new javax.swing.JMenuItem();
        seperator1 = new javax.swing.JPopupMenu.Separator();
        openFileButton = new javax.swing.JMenuItem();
        openProjectButton = new javax.swing.JMenuItem();
        openFolderButton = new javax.swing.JMenuItem();
        seperator2 = new javax.swing.JPopupMenu.Separator();
        saveButton = new javax.swing.JMenuItem();
        saveAsButton = new javax.swing.JMenuItem();
        seperator3 = new javax.swing.JPopupMenu.Separator();
        quitButton = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        undoButton = new javax.swing.JMenuItem();
        redoButton = new javax.swing.JMenuItem();
        seperator4 = new javax.swing.JPopupMenu.Separator();
        selectAllButton = new javax.swing.JMenuItem();
        cutButton = new javax.swing.JMenuItem();
        copyButton = new javax.swing.JMenuItem();
        pasteButton = new javax.swing.JMenuItem();
        seperator5 = new javax.swing.JPopupMenu.Separator();
        findReplaceButton = new javax.swing.JMenuItem();
        toolsMenu = new javax.swing.JMenu();
        submissionMenu = new javax.swing.JMenu();
        registerButton = new javax.swing.JMenuItem();
        loginButton = new javax.swing.JMenuItem();
        seperator6 = new javax.swing.JPopupMenu.Separator();
        templatesMenu = new javax.swing.JMenu();
        newTemplateButton = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        placeHolderMenu1 = new javax.swing.JMenuItem();
        placeHolderMenu2 = new javax.swing.JMenuItem();
        placeHolderMenu3 = new javax.swing.JMenuItem();
        insertJavadocButton = new javax.swing.JMenuItem();
        seperator7 = new javax.swing.JPopupMenu.Separator();
        javadocButton = new javax.swing.JMenuItem();
        jarButton = new javax.swing.JMenuItem();
        seperator8 = new javax.swing.JPopupMenu.Separator();
        compileButton = new javax.swing.JMenuItem();
        runButton = new javax.swing.JMenuItem();
        compileRunButton = new javax.swing.JMenuItem();
        resetButton = new javax.swing.JMenuItem();
        seperator9 = new javax.swing.JPopupMenu.Separator();
        preferencesButton = new javax.swing.JMenuItem();
        windowMenu = new javax.swing.JMenu();
        fileTrackerButton = new javax.swing.JCheckBoxMenuItem();
        methodSummaryButton = new javax.swing.JCheckBoxMenuItem();
        outputsPaneButton = new javax.swing.JCheckBoxMenuItem();
        seperator10 = new javax.swing.JPopupMenu.Separator();
        restoreButton = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        apiButton = new javax.swing.JMenuItem();
        tutorialsButton = new javax.swing.JMenuItem();
        seperator11 = new javax.swing.JPopupMenu.Separator();
        helpContentsButton = new javax.swing.JMenuItem();
        aboutButton = new javax.swing.JMenuItem();

        preferencesFrame.setTitle("Preferences");
        preferencesFrame.setResizable(false);

        idePreferencesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Toolbar"));
        idePreferencesPanel.setLayout(new java.awt.GridLayout(4, 4));

        newCheck.setSelected(true);
        newCheck.setText("New");
        idePreferencesPanel.add(newCheck);

        openCheck.setSelected(true);
        openCheck.setText("Open");
        idePreferencesPanel.add(openCheck);

        saveCheck.setSelected(true);
        saveCheck.setText("Save");
        idePreferencesPanel.add(saveCheck);

        undoCheck.setSelected(true);
        undoCheck.setText("Undo");
        idePreferencesPanel.add(undoCheck);

        redoCheck.setSelected(true);
        redoCheck.setText("Redo");
        idePreferencesPanel.add(redoCheck);

        compileCheck.setSelected(true);
        compileCheck.setText("Compile");
        idePreferencesPanel.add(compileCheck);

        runCheck.setSelected(true);
        runCheck.setText("Run");
        idePreferencesPanel.add(runCheck);

        compileRunCheck.setSelected(true);
        compileRunCheck.setText("Compile&Run");
        idePreferencesPanel.add(compileRunCheck);

        resetCheck.setSelected(true);
        resetCheck.setText("Reset");
        idePreferencesPanel.add(resetCheck);

        jarCheck.setSelected(true);
        jarCheck.setText("Export Jar");
        idePreferencesPanel.add(jarCheck);

        javadocCheck.setSelected(true);
        javadocCheck.setText("Javadoc");
        idePreferencesPanel.add(javadocCheck);

        apiCheck.setSelected(true);
        apiCheck.setText("API Link");
        idePreferencesPanel.add(apiCheck);

        helpCheck.setSelected(true);
        helpCheck.setText("Help");
        idePreferencesPanel.add(helpCheck);

        loginCheck.setSelected(true);
        loginCheck.setText("Login");
        idePreferencesPanel.add(loginCheck);

        toolbarPreferencesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("IDE"));

        themeLabel.setText("Editor Theme");

        fontLabel.setText("Editor Font");

        indentLabel.setText("Indent Level:");

        lineNumbersCheck.setSelected(true);
        lineNumbersCheck.setText("Display Line Numbers");
        lineNumbersCheck.setVerifyInputWhenFocusTarget(false);

        themeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default" }));

        selectFontButton.setText("Select Font");

        fontTextField.setEditable(false);
        fontTextField.setText("Consolas - 14");

        indentTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        indentTextField.setText("4");

        autosaveTextField.setText("5");

        minsLabel.setText("mins");

        showHelpCheck.setText("Show Help for Errors");

        autosaveCheck.setText("Autosave in");

        jLabel1.setText("Workspace Folder:");

        fontTextField1.setEditable(false);
        fontTextField1.setText("C:\\Users\\User\\Documents");

        selectFontButton1.setText("Browse");

        javax.swing.GroupLayout toolbarPreferencesPanelLayout = new javax.swing.GroupLayout(toolbarPreferencesPanel);
        toolbarPreferencesPanel.setLayout(toolbarPreferencesPanelLayout);
        toolbarPreferencesPanelLayout.setHorizontalGroup(
            toolbarPreferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarPreferencesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toolbarPreferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarPreferencesPanelLayout.createSequentialGroup()
                        .addGroup(toolbarPreferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(toolbarPreferencesPanelLayout.createSequentialGroup()
                                .addComponent(indentLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(indentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(themeLabel)
                            .addComponent(fontLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(toolbarPreferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarPreferencesPanelLayout.createSequentialGroup()
                                .addComponent(showHelpCheck)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarPreferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(themeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarPreferencesPanelLayout.createSequentialGroup()
                                    .addComponent(fontTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(selectFontButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(toolbarPreferencesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fontTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectFontButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolbarPreferencesPanelLayout.createSequentialGroup()
                        .addComponent(lineNumbersCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(autosaveCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(autosaveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minsLabel)))
                .addContainerGap())
        );
        toolbarPreferencesPanelLayout.setVerticalGroup(
            toolbarPreferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarPreferencesPanelLayout.createSequentialGroup()
                .addGroup(toolbarPreferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themeLabel)
                    .addComponent(themeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(toolbarPreferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fontLabel)
                    .addComponent(selectFontButton)
                    .addComponent(fontTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(toolbarPreferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(toolbarPreferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(showHelpCheck, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(indentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(indentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(toolbarPreferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lineNumbersCheck)
                    .addComponent(autosaveCheck)
                    .addComponent(autosaveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minsLabel))
                .addGap(18, 18, 18)
                .addGroup(toolbarPreferencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fontTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFontButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout preferencesFrameLayout = new javax.swing.GroupLayout(preferencesFrame.getContentPane());
        preferencesFrame.getContentPane().setLayout(preferencesFrameLayout);
        preferencesFrameLayout.setHorizontalGroup(
            preferencesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preferencesFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(preferencesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toolbarPreferencesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idePreferencesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        preferencesFrameLayout.setVerticalGroup(
            preferencesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preferencesFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toolbarPreferencesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idePreferencesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        findReplaceFrame.setTitle("Find / Replace");
        findReplaceFrame.setResizable(false);

        replaceButton.setText("Replace");

        replaceAllButton.setText("Replace All");

        findLabel.setText("Find what:");

        replaceLabel.setText("Replace with:");

        findTextField.setText(" ");

        replaceTextField.setText(" ");

        nextButton.setText("Next");

        previousButton.setText("Previous");

        javax.swing.GroupLayout findReplacePanelLayout = new javax.swing.GroupLayout(findReplacePanel);
        findReplacePanel.setLayout(findReplacePanelLayout);
        findReplacePanelLayout.setHorizontalGroup(
            findReplacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findReplacePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(findReplacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(findReplacePanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(findReplacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(findLabel)
                            .addComponent(replaceLabel)))
                    .addGroup(findReplacePanelLayout.createSequentialGroup()
                        .addComponent(previousButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(findReplacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findReplacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(replaceTextField)
                        .addComponent(findTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findReplacePanelLayout.createSequentialGroup()
                        .addComponent(replaceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(replaceAllButton)))
                .addContainerGap())
        );
        findReplacePanelLayout.setVerticalGroup(
            findReplacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findReplacePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(findReplacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findLabel))
                .addGap(18, 18, 18)
                .addGroup(findReplacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(replaceLabel))
                .addGap(18, 18, 18)
                .addGroup(findReplacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceButton)
                    .addComponent(previousButton)
                    .addComponent(replaceAllButton)
                    .addComponent(nextButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout findReplaceFrameLayout = new javax.swing.GroupLayout(findReplaceFrame.getContentPane());
        findReplaceFrame.getContentPane().setLayout(findReplaceFrameLayout);
        findReplaceFrameLayout.setHorizontalGroup(
            findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(findReplacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        findReplaceFrameLayout.setVerticalGroup(
            findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(findReplacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainSplitPane.setDividerLocation(300);
        mainSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topSplitPane.setDividerLocation(200);
        topSplitPane.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                topSplitPanePropertyChange(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("workspace");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab01");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("src");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("HelloWorld.java");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("classes");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("HelloWorld.class");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("doc");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab02");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab03");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("src");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Person.java");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Student.java");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Test.java");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("classes");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Person.class");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Student.class");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Test.class");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("doc");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab04");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab05");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab06");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab07");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab08");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab09");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab10");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        placeHolderFileExplorer.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        explorerScrollPane.setViewportView(placeHolderFileExplorer);

        topSplitPane.setLeftComponent(explorerScrollPane);

        topLeftSplitPane.setDividerLocation(700);
        topLeftSplitPane.setLeftComponent(textTabs);
        textTabs.getAccessibleContext().setAccessibleName("");

        methodSummary.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("HelloWorld.java");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("main( String[]) : void");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("greeting() : String");
        treeNode1.add(treeNode2);
        methodSummary.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        methodSummaryScrollPane.setViewportView(methodSummary);

        topLeftSplitPane.setRightComponent(methodSummaryScrollPane);

        javax.swing.GroupLayout editorAndMethodSummaryPanelLayout = new javax.swing.GroupLayout(editorAndMethodSummaryPanel);
        editorAndMethodSummaryPanel.setLayout(editorAndMethodSummaryPanelLayout);
        editorAndMethodSummaryPanelLayout.setHorizontalGroup(
            editorAndMethodSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topLeftSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
        );
        editorAndMethodSummaryPanelLayout.setVerticalGroup(
            editorAndMethodSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topLeftSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );

        topSplitPane.setRightComponent(editorAndMethodSummaryPanel);

        mainSplitPane.setTopComponent(topSplitPane);

        statusArea.setColumns(20);
        statusArea.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        statusArea.setRows(5);
        statusScrollPane.setViewportView(statusArea);

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );

        outputTabs.addTab("Status", statusPanel);

        consoleOutputPanel.setPreferredSize(new java.awt.Dimension(682, 200));

        consoleOutputArea.setColumns(20);
        consoleOutputArea.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        consoleOutputArea.setRows(5);
        consoleOutputScrollPane.setViewportView(consoleOutputArea);

        javax.swing.GroupLayout consoleOutputPanelLayout = new javax.swing.GroupLayout(consoleOutputPanel);
        consoleOutputPanel.setLayout(consoleOutputPanelLayout);
        consoleOutputPanelLayout.setHorizontalGroup(
            consoleOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(consoleInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
            .addComponent(consoleOutputScrollPane)
        );
        consoleOutputPanelLayout.setVerticalGroup(
            consoleOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consoleOutputPanelLayout.createSequentialGroup()
                .addComponent(consoleOutputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(consoleInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        outputTabs.addTab("Console Output", consoleOutputPanel);

        compilerOutputArea.setColumns(20);
        compilerOutputArea.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        compilerOutputArea.setRows(5);
        compilerOutputScrollPane.setViewportView(compilerOutputArea);

        javax.swing.GroupLayout compilerOutputPanelLayout = new javax.swing.GroupLayout(compilerOutputPanel);
        compilerOutputPanel.setLayout(compilerOutputPanelLayout);
        compilerOutputPanelLayout.setHorizontalGroup(
            compilerOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(compilerOutputScrollPane)
        );
        compilerOutputPanelLayout.setVerticalGroup(
            compilerOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(compilerOutputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );

        outputTabs.addTab("Compiler Output", compilerOutputPanel);

        javax.swing.GroupLayout outputsPanelLayout = new javax.swing.GroupLayout(outputsPanel);
        outputsPanel.setLayout(outputsPanelLayout);
        outputsPanelLayout.setHorizontalGroup(
            outputsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outputTabs)
        );
        outputsPanelLayout.setVerticalGroup(
            outputsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outputTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );

        outputTabs.getAccessibleContext().setAccessibleName("t3");

        mainSplitPane.setRightComponent(outputsPanel);

        newTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/new.png"))); // NOI18N
        newTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newToolActionPerformed(evt);
            }
        });

        openTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/open.png"))); // NOI18N
        openTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openToolActionPerformed(evt);
            }
        });

        saveTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/save.png"))); // NOI18N
        saveTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToolActionPerformed(evt);
            }
        });

        undoTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/undo.png"))); // NOI18N

        redoTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/redo.png"))); // NOI18N

        resetTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/reset.png"))); // NOI18N

        javadocTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/doc.png"))); // NOI18N

        jarTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/jar.png"))); // NOI18N

        compileTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/compile.png"))); // NOI18N

        runTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/run.png"))); // NOI18N

        compileRunTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/comprun.png"))); // NOI18N

        apiTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/api.png"))); // NOI18N

        helpTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/help.png"))); // NOI18N

        loginTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/login.png"))); // NOI18N

        closeTool.setText("X");
        closeTool.setToolTipText("");
        closeTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeToolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolbarPanelLayout = new javax.swing.GroupLayout(toolbarPanel);
        toolbarPanel.setLayout(toolbarPanelLayout);
        toolbarPanelLayout.setHorizontalGroup(
            toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarPanelLayout.createSequentialGroup()
                .addComponent(newTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(openTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(saveTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(undoTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(redoTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(compileTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(runTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(compileRunTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(resetTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jarTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(javadocTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(apiTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(helpTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeTool)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        toolbarPanelLayout.setVerticalGroup(
            toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(openTool, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(saveTool, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(undoTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(redoTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(resetTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(compileTool, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jarTool, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(javadocTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(compileRunTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(apiTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(runTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(newTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(helpTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(loginTool, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(closeTool, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        fileMenu.setText("File");

        newFileButton.setText("New Java Class");
        fileMenu.add(newFileButton);

        newProjectButton.setText("New Project");
        fileMenu.add(newProjectButton);
        fileMenu.add(seperator1);

        openFileButton.setText("Open File");
        fileMenu.add(openFileButton);

        openProjectButton.setText("Open Project");
        fileMenu.add(openProjectButton);

        openFolderButton.setText("Open Folder");
        fileMenu.add(openFolderButton);
        fileMenu.add(seperator2);

        saveButton.setText("Save");
        fileMenu.add(saveButton);

        saveAsButton.setText("Save As...");
        fileMenu.add(saveAsButton);
        fileMenu.add(seperator3);

        quitButton.setText("Quit");
        fileMenu.add(quitButton);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");

        undoButton.setText("Undo");
        editMenu.add(undoButton);

        redoButton.setText("Redo");
        editMenu.add(redoButton);
        editMenu.add(seperator4);

        selectAllButton.setText("Select all");
        editMenu.add(selectAllButton);

        cutButton.setText("Cut");
        editMenu.add(cutButton);

        copyButton.setText("Copy");
        editMenu.add(copyButton);

        pasteButton.setText("Paste");
        editMenu.add(pasteButton);
        editMenu.add(seperator5);

        findReplaceButton.setText("Find/Replace");
        findReplaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findReplaceButtonActionPerformed(evt);
            }
        });
        editMenu.add(findReplaceButton);

        menuBar.add(editMenu);

        toolsMenu.setText("Tools");

        submissionMenu.setText("Submission System");

        registerButton.setText("Register");
        submissionMenu.add(registerButton);

        loginButton.setText("Login");
        submissionMenu.add(loginButton);

        toolsMenu.add(submissionMenu);
        toolsMenu.add(seperator6);

        templatesMenu.setText("Code Templates");

        newTemplateButton.setText("New Template");
        templatesMenu.add(newTemplateButton);
        templatesMenu.add(jSeparator6);

        placeHolderMenu1.setText("CS101 - Console");
        templatesMenu.add(placeHolderMenu1);

        placeHolderMenu2.setText("CS102 - Frame");
        templatesMenu.add(placeHolderMenu2);

        placeHolderMenu3.setText("CustomTemp1");
        templatesMenu.add(placeHolderMenu3);

        toolsMenu.add(templatesMenu);

        insertJavadocButton.setText("Insert Javadoc Comment");
        toolsMenu.add(insertJavadocButton);
        toolsMenu.add(seperator7);

        javadocButton.setText("Create Javadoc");
        toolsMenu.add(javadocButton);

        jarButton.setText("Create Jar File");
        toolsMenu.add(jarButton);
        toolsMenu.add(seperator8);

        compileButton.setText("Compile");
        toolsMenu.add(compileButton);

        runButton.setText("Run");
        toolsMenu.add(runButton);

        compileRunButton.setText("Compile & Run");
        toolsMenu.add(compileRunButton);

        resetButton.setText("Reset Interactions");
        toolsMenu.add(resetButton);
        toolsMenu.add(seperator9);

        preferencesButton.setText("Preferences");
        preferencesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferencesButtonActionPerformed(evt);
            }
        });
        toolsMenu.add(preferencesButton);

        menuBar.add(toolsMenu);

        windowMenu.setText("Window");

        fileTrackerButton.setSelected(true);
        fileTrackerButton.setText("File Tracker");
        windowMenu.add(fileTrackerButton);

        methodSummaryButton.setSelected(true);
        methodSummaryButton.setText("Method Summary");
        windowMenu.add(methodSummaryButton);

        outputsPaneButton.setSelected(true);
        outputsPaneButton.setText("Outputs Pane");
        windowMenu.add(outputsPaneButton);
        windowMenu.add(seperator10);

        restoreButton.setText("Restore to default");
        windowMenu.add(restoreButton);

        menuBar.add(windowMenu);

        helpMenu.setText("Help");

        apiButton.setText("Java API");
        helpMenu.add(apiButton);

        tutorialsButton.setText("Java Tutorials");
        helpMenu.add(tutorialsButton);
        helpMenu.add(seperator11);

        helpContentsButton.setText("Help Contents");
        helpMenu.add(helpContentsButton);

        aboutButton.setText("About");
        helpMenu.add(aboutButton);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toolbarPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainSplitPane))
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(toolbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(mainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preferencesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferencesButtonActionPerformed
        showPreferences();
    }//GEN-LAST:event_preferencesButtonActionPerformed

    private void topSplitPanePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_topSplitPanePropertyChange
        divLoc1 = topSplitPane.getDividerLocation();
    }//GEN-LAST:event_topSplitPanePropertyChange

    private void findReplaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findReplaceButtonActionPerformed
        showFindAndReplace();
    }//GEN-LAST:event_findReplaceButtonActionPerformed

    private void saveToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToolActionPerformed
        saveCurrentFile();
    }//GEN-LAST:event_saveToolActionPerformed

    private void openToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openToolActionPerformed
        openFile();
    }//GEN-LAST:event_openToolActionPerformed

    private void newToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newToolActionPerformed
        newFile();
    }//GEN-LAST:event_newToolActionPerformed

    private void closeToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeToolActionPerformed
        closeActiveFile();
    }//GEN-LAST:event_closeToolActionPerformed

    /** Sets LookAndFeel to the given name.*/
    public static void setLookAndFeel (String lookAndFeel) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (lookAndFeel.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }        
    }
    
    /** This class is used for listening resize events of the window. */
    class MyComponentListener implements ComponentListener {
        public void componentResized(ComponentEvent e) {
            arrangeComponents();
        }
        public void componentHidden(ComponentEvent e) {}
        public void componentMoved(ComponentEvent e) {}
        public void componentShown(ComponentEvent e) {}
    }
    
    private void addTextArea( String tabName, String content) throws IOException {
        JPanel panel = new JPanel( new BorderLayout());
        RSyntaxTextArea textArea = new RSyntaxTextArea(20, 60);
        textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
        textArea.setCodeFoldingEnabled(true);
        Theme theme = Theme.load(getClass().getResourceAsStream(
        "/org/fife/ui/rsyntaxtextarea/themes/default.xml"));
        theme.apply(textArea);
        textArea.setFont(new Font("Consolas", Font.PLAIN, 16));
        
        textArea.setText( content);// + "" + System.getenv("JAVA_HOME") + "\n\r" + javax.tools.ToolProvider.getSystemJavaCompiler());
        
        textAreas.add( textArea);
        
        RTextScrollPane sp = new RTextScrollPane(textArea);
        panel.add( sp);
        textTabs.add(tabName, panel);
    }
    
    private void initFrame() throws IOException {
        divLoc1 = 200;
        setTitle("Call-IDE");
        setIconImage(ImageIO.read(getClass().getResource("/uidesign/icon.jpg"))); 
        setSize(new Dimension(1400, 700));
        setLocationRelativeTo(null);
        arrangeComponents();
        addComponentListener(new MyComponentListener());
        setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        
    }
   /*rivate void findAndReplace()
    {
       
    }*/
    
    /** Arranges the split pane divider locations for a better look. */
    private void arrangeComponents() {
        topSplitPane.setDividerLocation(divLoc1);
        mainSplitPane.setDividerLocation(mainSplitPane.getHeight() - 200);
        topLeftSplitPane.setDividerLocation(topLeftSplitPane.getWidth() - 250);
    }
    
    private void showPreferences() {
        preferencesFrame.pack();
        preferencesFrame.setLocationRelativeTo(this);
        preferencesFrame.setVisible(true);
        preferencesFrame.pack();
    }
    
    private int getWordCounter( )
    {
        return this.wordCounter;
    }
    private void setWordCounter( int counter)
    {
        wordCounter = counter;
    }
     
    private void setSearchResult( SearchResult result)
    {
        searchResult = result;
    }
    private void showFindAndReplace()
    {
        
        SearchContext searchContext = new SearchContext("");
        
        findTextField.setText("");
        replaceTextField.setText("");
        JButton[] buttons = new JButton[4];
        buttons[0] = nextButton;
        buttons[1] = previousButton;
        buttons[2] = replaceButton;
        buttons[3] = replaceAllButton;
        setWordCounter( 0);
        
        nextButton.addActionListener(new ActionListener(){
                        int counter2;
			@Override
			public void actionPerformed(ActionEvent arg0) {
                               counter2 = getWordCounter();
                               searchContext.setSearchForward(true);
                               if(!findTextField.getText().equals(searchContext.getSearchFor()))
                               {
                                    counter2 = 1;
                                    getActiveTextArea().setCaretPosition(0);
                                    searchContext.setSearchFor(findTextField.getText());
                                    searchResult = SearchEngine.find(getActiveTextArea(), searchContext);
                                    System.out.println( searchResult.getMarkedCount()+ " " + counter2 + "1ilk if " + getActiveTextArea().getCaretPosition());
                               }
                               else
                               {
                                    if (!searchContext.getSearchFor().isEmpty()) {
                                        
                                        if( searchResult.getMarkedCount() == counter2)
                                        {
                                           
                                            getActiveTextArea().setCaretPosition(0);
                                            SearchEngine.find(getActiveTextArea(), searchContext);
                                            counter2 = 1;
                                            System.out.println( searchResult.getMarkedCount()+ " " + counter2 + "1iki if " + getActiveTextArea().getCaretPosition());
                                        }
                                        else
                                        {                                            
                                            getActiveTextArea().setCaretPosition(getActiveTextArea().getCaretPosition());
                                            SearchEngine.find(getActiveTextArea(), searchContext);
                                            counter2++;
                                            System.out.println( searchResult.getMarkedCount()+ " " + counter2 + "1üç if " + getActiveTextArea().getCaretPosition());
                                        }  
                                    }
                               }
                               setSearchResult( searchResult);
                               setWordCounter( counter2);
			}
                        
                          	
        });
        previousButton.addActionListener(new ActionListener(){
                        
                        
                        int counter;
			@Override
			public void actionPerformed(ActionEvent arg0) {
                               counter = getWordCounter();
                               searchContext.setSearchForward(false);
                               if(!findTextField.getText().equals(searchContext.getSearchFor()))
                               {
                                    searchContext.setSearchFor(findTextField.getText());
                                    getActiveTextArea().setCaretPosition(getActiveTextArea().getText().length());
                                    searchResult = SearchEngine.find(getActiveTextArea(), searchContext);
                                    counter = searchResult.getMarkedCount();
                                    System.out.println( searchResult.getMarkedCount()+ " " + counter + "2ilk if " +getActiveTextArea().getCaretPosition());
                               }
                               else
                               {
                                    if (!searchContext.getSearchFor().isEmpty()) {
                                        if( 1 == counter)
                                        {
                                            getActiveTextArea().setCaretPosition(getActiveTextArea().getText().length());
                                            searchResult = SearchEngine.find(getActiveTextArea(), searchContext);
                                            
                                            counter = searchResult.getMarkedCount();
                                            System.out.println( searchResult.getMarkedCount()+ " " + counter + "2iki if "+ getActiveTextArea().getCaretPosition());
                                        }
                                        else
                                        {                                            
                                            getActiveTextArea().setCaretPosition(getActiveTextArea().getCaretPosition() - 1);
                                            searchResult = SearchEngine.find(getActiveTextArea(), searchContext);
                                            counter--;
                                            System.out.println( searchResult.getMarkedCount()+ " " + counter + "2üç if " + getActiveTextArea().getCaretPosition());
                                        }  
                                    }
                               }
                               setSearchResult( searchResult);
                               setWordCounter(counter);
				
			}
        	
        });
        replaceButton.addActionListener(new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent arg0) {
				searchContext.setReplaceWith( replaceTextField.getText());
				searchContext.setSearchFor(findTextField.getText());
				if( !searchContext.getSearchFor().isEmpty() && !searchContext.getReplaceWith().isEmpty())
                                {
                                    SearchEngine.replace(getActiveTextArea(),searchContext);
                                    setWordCounter( getWordCounter()-1);
                                    System.out.println(getWordCounter());
                                    System.out.println(searchResult.getMarkedCount());
                                    searchResult.setMarkedCount(searchResult.getMarkedCount() - 1);
                                    getActiveTextArea().setCaretPosition( getActiveTextArea().getCaretPosition() - 1);
                                }
				
			}
        	
        });
        replaceAllButton.addActionListener(new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent arg0) {
				searchContext.setReplaceWith( replaceTextField.getText());
				searchContext.setSearchFor(findTextField.getText());
				if( !searchContext.getSearchFor().isEmpty() && !searchContext.getReplaceWith().isEmpty())
				{
                                    getActiveTextArea().setCaretPosition(0);
                                    SearchEngine.replaceAll(getActiveTextArea(), searchContext);
                                    setWordCounter( 0);
                                    System.out.println(getWordCounter());
				}
                                
			}
        	
        });
        findReplaceFrame.pack();
        findReplaceFrame.setLocationRelativeTo(this);
        findReplaceFrame.addWindowListener(new WindowAdapter(){
            
            @Override
            public void	windowClosing(WindowEvent e)
            {
                
                for( JButton currentButton: buttons)
                        for( ActionListener al : currentButton.getActionListeners() ) {
                         currentButton.removeActionListener( al );
                        }
            }
        
    });
    
        
    
        findReplaceFrame.setVisible(true);
    }
    
    private void saveCurrentFile() {
        try {
            File file = getActiveFile();

            if (file == null) {
                JFileChooser chooser = new JFileChooser();
                if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                    file = chooser.getSelectedFile();
                    files.set(textTabs.getSelectedIndex(), file);
                    FileSaver saver = new FileSaver(file);
                    saver.save( getActiveContent());
                    printStatus("File saved as: " + file.getAbsolutePath());
                    textTabs.setTitleAt(textTabs.getSelectedIndex(), file.getName());
                }
            }
            else {
                FileSaver saver = new FileSaver(file);
                saver.save( getActiveContent());
                printStatus("File updated: " + file.getAbsolutePath());
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void openFile() {
        try {
            JFileChooser chooser = new JFileChooser();
            if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                File file = chooser.getSelectedFile();
                for (int i = 0; i < files.size(); i++) {
                    File checkFile = files.get(i);
                    if (checkFile != null && file.getAbsolutePath().equals(checkFile.getAbsolutePath())) {
                        textTabs.setSelectedIndex(i);
                        return;
                    }
                }
                addTextArea( file.getName(), ContentReader.read( file));
                files.add( file);
                textTabs.setSelectedIndex(textAreas.size() - 1);
                printStatus("File opened: " + file.getName());
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void newFile() {
        try {
            files.add( null);
            addTextArea( "Untitled " + untitledCount, "// Enter code here...");
            untitledCount++;
            textTabs.setSelectedIndex(textAreas.size() - 1);
        } catch( IOException e) {
            e.printStackTrace();
        }
    }
    
    private File getActiveFile() {
        int index = textTabs.getSelectedIndex();
        if (index >= files.size())
            return null;
        return files.get(index);
    }
    
    private String getActiveContent() {
        int index = textTabs.getSelectedIndex();
        RSyntaxTextArea textArea = textAreas.get(index);
        return textArea.getText();
    }
    
    private RSyntaxTextArea getActiveTextArea() {
        int index = textTabs.getSelectedIndex();
        return textAreas.get(index);
    }
    
    private void printStatus( String status) {
        statusArea.setText( statusArea.getText() + status + "\n");
        outputTabs.setSelectedIndex(0);
    }
    
    private void addExplorer() {
        // placeHolderFileExplorer.setVisible( false);
        // explorerScrollPane.setViewportView(new FileNavigator( "D:\\BAHADIR"));
    }
    
    private void closeActiveFile() {
        int index = textTabs.getSelectedIndex();
        if (index != -1) {
            files.remove( index);
            textAreas.remove( index);
            textTabs.remove( index);
        }
    }
    
    // Other Variables
    private ArrayList<RSyntaxTextArea> textAreas;
    private ArrayList<File> files;
    private int divLoc1; // The divider location of the left split pane.
    private int untitledCount;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutButton;
    private javax.swing.JMenuItem apiButton;
    private javax.swing.JCheckBox apiCheck;
    private javax.swing.JButton apiTool;
    private javax.swing.JCheckBox autosaveCheck;
    private javax.swing.JTextField autosaveTextField;
    private javax.swing.JButton closeTool;
    private javax.swing.JMenuItem compileButton;
    private javax.swing.JCheckBox compileCheck;
    private javax.swing.JMenuItem compileRunButton;
    private javax.swing.JCheckBox compileRunCheck;
    private javax.swing.JButton compileRunTool;
    private javax.swing.JButton compileTool;
    private javax.swing.JTextArea compilerOutputArea;
    private javax.swing.JPanel compilerOutputPanel;
    private javax.swing.JScrollPane compilerOutputScrollPane;
    private javax.swing.JTextField consoleInputField;
    private javax.swing.JTextArea consoleOutputArea;
    private javax.swing.JPanel consoleOutputPanel;
    private javax.swing.JScrollPane consoleOutputScrollPane;
    private javax.swing.JMenuItem copyButton;
    private javax.swing.JMenuItem cutButton;
    private javax.swing.JMenu editMenu;
    private javax.swing.JPanel editorAndMethodSummaryPanel;
    private javax.swing.JScrollPane explorerScrollPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JCheckBoxMenuItem fileTrackerButton;
    private javax.swing.JLabel findLabel;
    private javax.swing.JMenuItem findReplaceButton;
    private javax.swing.JFrame findReplaceFrame;
    private javax.swing.JPanel findReplacePanel;
    private javax.swing.JTextField findTextField;
    private javax.swing.JLabel fontLabel;
    private javax.swing.JTextField fontTextField;
    private javax.swing.JTextField fontTextField1;
    private javax.swing.JCheckBox helpCheck;
    private javax.swing.JMenuItem helpContentsButton;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton helpTool;
    private javax.swing.JPanel idePreferencesPanel;
    private javax.swing.JLabel indentLabel;
    private javax.swing.JTextField indentTextField;
    private javax.swing.JMenuItem insertJavadocButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenuItem jarButton;
    private javax.swing.JCheckBox jarCheck;
    private javax.swing.JButton jarTool;
    private javax.swing.JMenuItem javadocButton;
    private javax.swing.JCheckBox javadocCheck;
    private javax.swing.JButton javadocTool;
    private javax.swing.JCheckBox lineNumbersCheck;
    private javax.swing.JMenuItem loginButton;
    private javax.swing.JCheckBox loginCheck;
    private javax.swing.JButton loginTool;
    private javax.swing.JSplitPane mainSplitPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTree methodSummary;
    private javax.swing.JCheckBoxMenuItem methodSummaryButton;
    private javax.swing.JScrollPane methodSummaryScrollPane;
    private javax.swing.JLabel minsLabel;
    private javax.swing.JCheckBox newCheck;
    private javax.swing.JMenuItem newFileButton;
    private javax.swing.JMenuItem newProjectButton;
    private javax.swing.JMenuItem newTemplateButton;
    private javax.swing.JButton newTool;
    private javax.swing.JButton nextButton;
    private javax.swing.JCheckBox openCheck;
    private javax.swing.JMenuItem openFileButton;
    private javax.swing.JMenuItem openFolderButton;
    private javax.swing.JMenuItem openProjectButton;
    private javax.swing.JButton openTool;
    private javax.swing.JTabbedPane outputTabs;
    private javax.swing.JCheckBoxMenuItem outputsPaneButton;
    private javax.swing.JPanel outputsPanel;
    private javax.swing.JMenuItem pasteButton;
    private javax.swing.JTree placeHolderFileExplorer;
    private javax.swing.JMenuItem placeHolderMenu1;
    private javax.swing.JMenuItem placeHolderMenu2;
    private javax.swing.JMenuItem placeHolderMenu3;
    private javax.swing.JMenuItem preferencesButton;
    private javax.swing.JFrame preferencesFrame;
    private javax.swing.JButton previousButton;
    private javax.swing.JMenuItem quitButton;
    private javax.swing.JMenuItem redoButton;
    private javax.swing.JCheckBox redoCheck;
    private javax.swing.JButton redoTool;
    private javax.swing.JMenuItem registerButton;
    private javax.swing.JButton replaceAllButton;
    private javax.swing.JButton replaceButton;
    private javax.swing.JLabel replaceLabel;
    private javax.swing.JTextField replaceTextField;
    private javax.swing.JMenuItem resetButton;
    private javax.swing.JCheckBox resetCheck;
    private javax.swing.JButton resetTool;
    private javax.swing.JMenuItem restoreButton;
    private javax.swing.JMenuItem runButton;
    private javax.swing.JCheckBox runCheck;
    private javax.swing.JButton runTool;
    private javax.swing.JMenuItem saveAsButton;
    private javax.swing.JMenuItem saveButton;
    private javax.swing.JCheckBox saveCheck;
    private javax.swing.JButton saveTool;
    private javax.swing.JMenuItem selectAllButton;
    private javax.swing.JButton selectFontButton;
    private javax.swing.JButton selectFontButton1;
    private javax.swing.JPopupMenu.Separator seperator1;
    private javax.swing.JPopupMenu.Separator seperator10;
    private javax.swing.JPopupMenu.Separator seperator11;
    private javax.swing.JPopupMenu.Separator seperator2;
    private javax.swing.JPopupMenu.Separator seperator3;
    private javax.swing.JPopupMenu.Separator seperator4;
    private javax.swing.JPopupMenu.Separator seperator5;
    private javax.swing.JPopupMenu.Separator seperator6;
    private javax.swing.JPopupMenu.Separator seperator7;
    private javax.swing.JPopupMenu.Separator seperator8;
    private javax.swing.JPopupMenu.Separator seperator9;
    private javax.swing.JCheckBox showHelpCheck;
    private javax.swing.JTextArea statusArea;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JScrollPane statusScrollPane;
    private javax.swing.JMenu submissionMenu;
    private javax.swing.JMenu templatesMenu;
    private javax.swing.JTabbedPane textTabs;
    private javax.swing.JComboBox<String> themeComboBox;
    private javax.swing.JLabel themeLabel;
    private javax.swing.JPanel toolbarPanel;
    private javax.swing.JPanel toolbarPreferencesPanel;
    private javax.swing.JMenu toolsMenu;
    private javax.swing.JSplitPane topLeftSplitPane;
    private javax.swing.JSplitPane topSplitPane;
    private javax.swing.JMenuItem tutorialsButton;
    private javax.swing.JMenuItem undoButton;
    private javax.swing.JCheckBox undoCheck;
    private javax.swing.JButton undoTool;
    private javax.swing.JMenu windowMenu;
    // End of variables declaration//GEN-END:variables

}