/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uidesign;


import java.awt.*;
import java.awt.event.*;
import java.io.*;
import javax.swing.*;
import javax.imageio.ImageIO;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rsyntaxtextarea.Theme;
import org.fife.ui.rtextarea.RTextScrollPane;
import java.util.ArrayList;
import FileOperations.*;
import RunUtils.*;

/**
 *
 * @author bahadir.tuluce-ug
 */
public class MainFrame extends javax.swing.JFrame {
    
    /** Creates new form MainFrame. */
    public MainFrame() throws IOException {
        textAreas = new ArrayList<RSyntaxTextArea>();
        files = new ArrayList<File>();
        untitledCount = 1;
        initComponents();
        newFile();
        initFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propertiesFrame = new javax.swing.JFrame();
        jPanel10 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton28 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        findReplaceFrame = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        textTabs = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        outputTabs = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        statusArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        consoleOutputArea = new javax.swing.JTextArea();
        consoleInputField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        compilerOutputArea = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        newTool = new javax.swing.JButton();
        openTool = new javax.swing.JButton();
        saveTool = new javax.swing.JButton();
        undoTool = new javax.swing.JButton();
        redoTool = new javax.swing.JButton();
        resetTool = new javax.swing.JButton();
        javadocTool = new javax.swing.JButton();
        jarTool = new javax.swing.JButton();
        compileTool = new javax.swing.JButton();
        runTool = new javax.swing.JButton();
        compileRunTool = new javax.swing.JButton();
        apiTool = new javax.swing.JButton();
        helpTool = new javax.swing.JButton();
        loginTool = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newFileButton = new javax.swing.JMenuItem();
        newProjectButton = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        openFileButton = new javax.swing.JMenuItem();
        openProjectButton = new javax.swing.JMenuItem();
        openFolderButton = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        saveButton = new javax.swing.JMenuItem();
        saveAsButton = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        quitButton = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        undoButton = new javax.swing.JMenuItem();
        redoButton = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        selectAllButton = new javax.swing.JMenuItem();
        cutButton = new javax.swing.JMenuItem();
        copyButton = new javax.swing.JMenuItem();
        pasteButton = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        findReplaceButton = new javax.swing.JMenuItem();
        toolsMenu = new javax.swing.JMenu();
        submissionMenu = new javax.swing.JMenu();
        registerButton = new javax.swing.JMenuItem();
        loginButton = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        templatesMenu = new javax.swing.JMenu();
        newTemplateButton = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        insertJavadocButton = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        javadocButton = new javax.swing.JMenuItem();
        jarButton = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        compileButton = new javax.swing.JMenuItem();
        runButton = new javax.swing.JMenuItem();
        compileRunButton = new javax.swing.JMenuItem();
        resetButton = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        preferencesButton = new javax.swing.JMenuItem();
        windowMenu = new javax.swing.JMenu();
        fileTrackerButton = new javax.swing.JCheckBoxMenuItem();
        methodSummaryButton = new javax.swing.JCheckBoxMenuItem();
        outputsPaneButton = new javax.swing.JCheckBoxMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        restoreButton = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        apiButton = new javax.swing.JMenuItem();
        tutorialsButton = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        helpContentsButton = new javax.swing.JMenuItem();
        aboutButton = new javax.swing.JMenuItem();

        propertiesFrame.setTitle("Preferences");

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Toolbar"));
        jPanel10.setLayout(new java.awt.GridLayout(4, 4));

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("New");
        jPanel10.add(jCheckBox2);

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Open");
        jPanel10.add(jCheckBox3);

        jCheckBox4.setSelected(true);
        jCheckBox4.setText("Save");
        jPanel10.add(jCheckBox4);

        jCheckBox5.setSelected(true);
        jCheckBox5.setText("Undo");
        jPanel10.add(jCheckBox5);

        jCheckBox6.setSelected(true);
        jCheckBox6.setText("Redo");
        jPanel10.add(jCheckBox6);

        jCheckBox7.setSelected(true);
        jCheckBox7.setText("Compile");
        jPanel10.add(jCheckBox7);

        jCheckBox8.setSelected(true);
        jCheckBox8.setText("Run");
        jPanel10.add(jCheckBox8);

        jCheckBox9.setSelected(true);
        jCheckBox9.setText("Compile&Run");
        jPanel10.add(jCheckBox9);

        jCheckBox10.setSelected(true);
        jCheckBox10.setText("Reset");
        jPanel10.add(jCheckBox10);

        jCheckBox11.setSelected(true);
        jCheckBox11.setText("Export Jar");
        jPanel10.add(jCheckBox11);

        jCheckBox12.setSelected(true);
        jCheckBox12.setText("Javadoc");
        jPanel10.add(jCheckBox12);

        jCheckBox13.setSelected(true);
        jCheckBox13.setText("API Link");
        jPanel10.add(jCheckBox13);

        jCheckBox15.setSelected(true);
        jCheckBox15.setText("Help");
        jPanel10.add(jCheckBox15);

        jCheckBox18.setSelected(true);
        jCheckBox18.setText("Login");
        jPanel10.add(jCheckBox18);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("IDE"));

        jLabel1.setText("Editor Theme");

        jLabel2.setText("Editor Font");

        jLabel3.setText("Indent Level");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Display Line Numbers");
        jCheckBox1.setVerifyInputWhenFocusTarget(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default" }));

        jButton28.setText("Select Font");

        jTextField2.setEditable(false);
        jTextField2.setText("Consolas - 14");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("4");

        jTextField4.setText("5");

        jLabel5.setText("mins");

        jCheckBox16.setText("Show Help for Errors");

        jCheckBox17.setText("Autosave in");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jCheckBox17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(jCheckBox16)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton28)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox17)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        javax.swing.GroupLayout propertiesFrameLayout = new javax.swing.GroupLayout(propertiesFrame.getContentPane());
        propertiesFrame.getContentPane().setLayout(propertiesFrameLayout);
        propertiesFrameLayout.setHorizontalGroup(
            propertiesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertiesFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertiesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        propertiesFrameLayout.setVerticalGroup(
            propertiesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertiesFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        findReplaceFrame.setTitle("Find / Replace");

        jLabel6.setText("Find what:");

        jLabel7.setText("Replace with:");

        jTextField5.setText(" ");

        jTextField6.setText(" ");

        jButton5.setText("Next");

        jButton6.setText("Previous");

        jButton7.setText("Replace");

        jButton16.setText("Replace All");

        javax.swing.GroupLayout findReplaceFrameLayout = new javax.swing.GroupLayout(findReplaceFrame.getContentPane());
        findReplaceFrame.getContentPane().setLayout(findReplaceFrameLayout);
        findReplaceFrameLayout.setHorizontalGroup(
            findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findReplaceFrameLayout.createSequentialGroup()
                .addGroup(findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(findReplaceFrameLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(jTextField5)))
                    .addGroup(findReplaceFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton16)))
                .addContainerGap())
        );
        findReplaceFrameLayout.setVerticalGroup(
            findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findReplaceFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setDividerLocation(300);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSplitPane1PropertyChange(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("workspace");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab01");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("src");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("HelloWorld.java");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("classes");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("HelloWorld.class");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("doc");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab02");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab03");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("src");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Person.java");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Student.java");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Test.java");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("classes");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Person.class");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Student.class");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Test.class");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("doc");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab04");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab05");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab06");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab07");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab08");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab09");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("lab10");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Files");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jSplitPane3.setDividerLocation(700);
        jSplitPane3.setLeftComponent(textTabs);
        textTabs.getAccessibleContext().setAccessibleName("");

        jTree2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("HelloWorld.java");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("main( String[]) : void");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("greeting() : String");
        treeNode1.add(treeNode2);
        jTree2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jTree2);

        jSplitPane3.setRightComponent(jScrollPane2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        jSplitPane2.setTopComponent(jSplitPane1);

        statusArea.setColumns(20);
        statusArea.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        statusArea.setRows(5);
        jScrollPane5.setViewportView(statusArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );

        outputTabs.addTab("Status", jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(682, 200));

        consoleOutputArea.setColumns(20);
        consoleOutputArea.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        consoleOutputArea.setRows(5);
        jScrollPane3.setViewportView(consoleOutputArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(consoleInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(consoleInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        outputTabs.addTab("Console Output", jPanel4);

        compilerOutputArea.setColumns(20);
        compilerOutputArea.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        compilerOutputArea.setRows(5);
        jScrollPane4.setViewportView(compilerOutputArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );

        outputTabs.addTab("Compiler Output", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outputTabs)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outputTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        outputTabs.getAccessibleContext().setAccessibleName("t3");

        jSplitPane2.setRightComponent(jPanel1);

        newTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/new.png"))); // NOI18N
        newTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newToolActionPerformed(evt);
            }
        });

        openTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/open.png"))); // NOI18N
        openTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openToolActionPerformed(evt);
            }
        });

        saveTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/save.png"))); // NOI18N
        saveTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToolActionPerformed(evt);
            }
        });

        undoTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/undo.png"))); // NOI18N

        redoTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/redo.png"))); // NOI18N

        resetTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/reset.png"))); // NOI18N

        javadocTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/doc.png"))); // NOI18N

        jarTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/jar.png"))); // NOI18N

        compileTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/compile.png"))); // NOI18N

        runTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/run.png"))); // NOI18N

        compileRunTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/comprun.png"))); // NOI18N

        apiTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/api.png"))); // NOI18N

        helpTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/help.png"))); // NOI18N

        loginTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/login.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(newTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(openTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(saveTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(undoTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(redoTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(compileTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(runTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(compileRunTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(resetTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jarTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(javadocTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(apiTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(helpTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(openTool, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(saveTool, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(undoTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(redoTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(resetTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(compileTool, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jarTool, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(javadocTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(compileRunTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(apiTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(runTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(newTool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(helpTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(loginTool, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        fileMenu.setText("File");

        newFileButton.setText("New Java Class");
        fileMenu.add(newFileButton);

        newProjectButton.setText("New Project");
        fileMenu.add(newProjectButton);
        fileMenu.add(jSeparator1);

        openFileButton.setText("Open File");
        fileMenu.add(openFileButton);

        openProjectButton.setText("Open Project");
        fileMenu.add(openProjectButton);

        openFolderButton.setText("Open Folder");
        fileMenu.add(openFolderButton);
        fileMenu.add(jSeparator2);

        saveButton.setText("Save");
        fileMenu.add(saveButton);

        saveAsButton.setText("Save As...");
        fileMenu.add(saveAsButton);
        fileMenu.add(jSeparator3);

        quitButton.setText("Quit");
        fileMenu.add(quitButton);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");

        undoButton.setText("Undo");
        editMenu.add(undoButton);

        redoButton.setText("Redo");
        editMenu.add(redoButton);
        editMenu.add(jSeparator4);

        selectAllButton.setText("Select all");
        editMenu.add(selectAllButton);

        cutButton.setText("Cut");
        editMenu.add(cutButton);

        copyButton.setText("Copy");
        editMenu.add(copyButton);

        pasteButton.setText("Paste");
        editMenu.add(pasteButton);
        editMenu.add(jSeparator5);

        findReplaceButton.setText("Find/Replace");
        findReplaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findReplaceButtonActionPerformed(evt);
            }
        });
        editMenu.add(findReplaceButton);

        menuBar.add(editMenu);

        toolsMenu.setText("Tools");

        submissionMenu.setText("Submission System");

        registerButton.setText("Register");
        submissionMenu.add(registerButton);

        loginButton.setText("Login");
        submissionMenu.add(loginButton);

        toolsMenu.add(submissionMenu);
        toolsMenu.add(jSeparator7);

        templatesMenu.setText("Code Templates");

        newTemplateButton.setText("New Template");
        templatesMenu.add(newTemplateButton);
        templatesMenu.add(jSeparator6);

        jMenuItem22.setText("CS101 - Console");
        templatesMenu.add(jMenuItem22);

        jMenuItem24.setText("CS102 - Frame");
        templatesMenu.add(jMenuItem24);

        jMenuItem25.setText("CustomTemp1");
        templatesMenu.add(jMenuItem25);

        toolsMenu.add(templatesMenu);

        insertJavadocButton.setText("Insert Javadoc Comment");
        toolsMenu.add(insertJavadocButton);
        toolsMenu.add(jSeparator12);

        javadocButton.setText("Create Javadoc");
        toolsMenu.add(javadocButton);

        jarButton.setText("Create Jar File");
        toolsMenu.add(jarButton);
        toolsMenu.add(jSeparator9);

        compileButton.setText("Compile");
        toolsMenu.add(compileButton);

        runButton.setText("Run");
        toolsMenu.add(runButton);

        compileRunButton.setText("Compile & Run");
        toolsMenu.add(compileRunButton);

        resetButton.setText("Reset Interactions");
        toolsMenu.add(resetButton);
        toolsMenu.add(jSeparator8);

        preferencesButton.setText("Preferences");
        preferencesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferencesButtonActionPerformed(evt);
            }
        });
        toolsMenu.add(preferencesButton);

        menuBar.add(toolsMenu);

        windowMenu.setText("Window");

        fileTrackerButton.setSelected(true);
        fileTrackerButton.setText("File Tracker");
        windowMenu.add(fileTrackerButton);

        methodSummaryButton.setSelected(true);
        methodSummaryButton.setText("Method Summary");
        windowMenu.add(methodSummaryButton);

        outputsPaneButton.setSelected(true);
        outputsPaneButton.setText("Outputs Pane");
        windowMenu.add(outputsPaneButton);
        windowMenu.add(jSeparator10);

        restoreButton.setText("Restore to default");
        windowMenu.add(restoreButton);

        menuBar.add(windowMenu);

        helpMenu.setText("Help");

        apiButton.setText("Java API");
        helpMenu.add(apiButton);

        tutorialsButton.setText("Java Tutorials");
        helpMenu.add(tutorialsButton);
        helpMenu.add(jSeparator11);

        helpContentsButton.setText("Help Contents");
        helpMenu.add(helpContentsButton);

        aboutButton.setText("About");
        helpMenu.add(aboutButton);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSplitPane2))
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preferencesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferencesButtonActionPerformed
        showPreferences();
    }//GEN-LAST:event_preferencesButtonActionPerformed

    private void jSplitPane1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSplitPane1PropertyChange
        divLoc1 = jSplitPane1.getDividerLocation();
    }//GEN-LAST:event_jSplitPane1PropertyChange

    private void findReplaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findReplaceButtonActionPerformed
        showFindAndReplace();
    }//GEN-LAST:event_findReplaceButtonActionPerformed

    private void saveToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToolActionPerformed
        saveCurrentFile();
    }//GEN-LAST:event_saveToolActionPerformed

    private void openToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openToolActionPerformed
        openFile();
    }//GEN-LAST:event_openToolActionPerformed

    private void newToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newToolActionPerformed
        newFile();
    }//GEN-LAST:event_newToolActionPerformed

    /** Sets LookAndFeel to the given name.*/
    public static void setLookAndFeel (String lookAndFeel) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (lookAndFeel.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }        
    }
    
    /** This class is used for listening resize events of the window. */
    class MyComponentListener implements ComponentListener {
        public void componentResized(ComponentEvent e) {
            arrangeComponents();
        }
        public void componentHidden(ComponentEvent e) {}
        public void componentMoved(ComponentEvent e) {}
        public void componentShown(ComponentEvent e) {}
    }
    
    private void addTextArea( String tabName, String content) throws IOException {
        JPanel panel = new JPanel( new BorderLayout());
        RSyntaxTextArea textArea = new RSyntaxTextArea(20, 60);
        textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
        textArea.setCodeFoldingEnabled(true);
        Theme theme = Theme.load(getClass().getResourceAsStream(
        "/org/fife/ui/rsyntaxtextarea/themes/default.xml"));
        theme.apply(textArea);
        textArea.setFont(new Font("Consolas", Font.PLAIN, 16));
        
        textArea.setText( content);// + "" + System.getenv("JAVA_HOME") + "\n\r" + javax.tools.ToolProvider.getSystemJavaCompiler());
        
        textAreas.add( textArea);
        
        RTextScrollPane sp = new RTextScrollPane(textArea);
        panel.add( sp);
        textTabs.add(tabName, panel);
    }
    
    private void initFrame() throws IOException {
        divLoc1 = 200;
        setTitle("Call-IDE");
        setIconImage(ImageIO.read(getClass().getResource("/uidesign/icon.jpg"))); 
        setSize(new Dimension(1400, 700));
        setLocationRelativeTo(null);
        arrangeComponents();
        addComponentListener(new MyComponentListener());
        setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }
    
    /** Arranges the split pane divider locations for a better look. */
    private void arrangeComponents() {
        jSplitPane1.setDividerLocation(divLoc1);
        jSplitPane2.setDividerLocation(jSplitPane2.getHeight() - 200);
        jSplitPane3.setDividerLocation(jSplitPane3.getWidth() - 250);
    }
    
    private void showPreferences() {
        propertiesFrame.pack();
        propertiesFrame.setLocationRelativeTo(this);
        propertiesFrame.setVisible(true);
    }
    
    private void showFindAndReplace() {
        findReplaceFrame.pack();
        findReplaceFrame.setLocationRelativeTo(this);
        findReplaceFrame.setVisible(true);
    }
    
    private void saveCurrentFile() {
        try {
            File file = getActiveFile();

            if (file == null) {
                JFileChooser chooser = new JFileChooser();
                if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                    file = chooser.getSelectedFile();
                    files.set(textTabs.getSelectedIndex(), file);
                    FileSaver saver = new FileSaver(file);
                    saver.save( getActiveContent());
                    printStatus("File saved as: " + file.getAbsolutePath());
                }
            }
            else {
                FileSaver saver = new FileSaver(file);
                saver.save( getActiveContent());
                printStatus("File updated: " + file.getAbsolutePath());
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void openFile() {
        try {
            JFileChooser chooser = new JFileChooser();
            if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                File file = chooser.getSelectedFile();
                addTextArea( file.getName(), ContentReader.read( file));
                files.add( file);
                textTabs.setSelectedIndex(textAreas.size() - 1);
                printStatus("File opened: " + file.getName());
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void newFile() {
        try {
            files.add( null);
            addTextArea( "Untitled " + untitledCount, "// Enter code here...");
            untitledCount++;
            textTabs.setSelectedIndex(textAreas.size() - 1);
        } catch( IOException e) {
            e.printStackTrace();
        }
    }
    
    private File getActiveFile() {
        int index = textTabs.getSelectedIndex();
        if (index >= files.size())
            return null;
        return files.get(index);
    }
    
    private String getActiveContent() {
        int index = textTabs.getSelectedIndex();
        RSyntaxTextArea textArea = textAreas.get(index);
        return textArea.getText();
    }
    
    private void printStatus( String status) {
        statusArea.setText( statusArea.getText() + status + "\n");
        outputTabs.setSelectedIndex(0);
    }
    
    // Other Variables
    private ArrayList<RSyntaxTextArea> textAreas;
    private ArrayList<File> files;
    private int divLoc1; // The divider location of the left split pane.
    private int untitledCount;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutButton;
    private javax.swing.JMenuItem apiButton;
    private javax.swing.JButton apiTool;
    private javax.swing.JMenuItem compileButton;
    private javax.swing.JMenuItem compileRunButton;
    private javax.swing.JButton compileRunTool;
    private javax.swing.JButton compileTool;
    private javax.swing.JTextArea compilerOutputArea;
    private javax.swing.JTextField consoleInputField;
    private javax.swing.JTextArea consoleOutputArea;
    private javax.swing.JMenuItem copyButton;
    private javax.swing.JMenuItem cutButton;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JCheckBoxMenuItem fileTrackerButton;
    private javax.swing.JMenuItem findReplaceButton;
    private javax.swing.JFrame findReplaceFrame;
    private javax.swing.JMenuItem helpContentsButton;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton helpTool;
    private javax.swing.JMenuItem insertJavadocButton;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTree jTree1;
    private javax.swing.JTree jTree2;
    private javax.swing.JMenuItem jarButton;
    private javax.swing.JButton jarTool;
    private javax.swing.JMenuItem javadocButton;
    private javax.swing.JButton javadocTool;
    private javax.swing.JMenuItem loginButton;
    private javax.swing.JButton loginTool;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JCheckBoxMenuItem methodSummaryButton;
    private javax.swing.JMenuItem newFileButton;
    private javax.swing.JMenuItem newProjectButton;
    private javax.swing.JMenuItem newTemplateButton;
    private javax.swing.JButton newTool;
    private javax.swing.JMenuItem openFileButton;
    private javax.swing.JMenuItem openFolderButton;
    private javax.swing.JMenuItem openProjectButton;
    private javax.swing.JButton openTool;
    private javax.swing.JTabbedPane outputTabs;
    private javax.swing.JCheckBoxMenuItem outputsPaneButton;
    private javax.swing.JMenuItem pasteButton;
    private javax.swing.JMenuItem preferencesButton;
    private javax.swing.JFrame propertiesFrame;
    private javax.swing.JMenuItem quitButton;
    private javax.swing.JMenuItem redoButton;
    private javax.swing.JButton redoTool;
    private javax.swing.JMenuItem registerButton;
    private javax.swing.JMenuItem resetButton;
    private javax.swing.JButton resetTool;
    private javax.swing.JMenuItem restoreButton;
    private javax.swing.JMenuItem runButton;
    private javax.swing.JButton runTool;
    private javax.swing.JMenuItem saveAsButton;
    private javax.swing.JMenuItem saveButton;
    private javax.swing.JButton saveTool;
    private javax.swing.JMenuItem selectAllButton;
    private javax.swing.JTextArea statusArea;
    private javax.swing.JMenu submissionMenu;
    private javax.swing.JMenu templatesMenu;
    private javax.swing.JTabbedPane textTabs;
    private javax.swing.JMenu toolsMenu;
    private javax.swing.JMenuItem tutorialsButton;
    private javax.swing.JMenuItem undoButton;
    private javax.swing.JButton undoTool;
    private javax.swing.JMenu windowMenu;
    // End of variables declaration//GEN-END:variables

}